general:
  gui_username: admin
  gui_password: admin
  private_key: myK3yIsAwesome!
  redis_host: localhost:6379
  redis_password: 
coop:
  latitude: 43.388352
  longitude: 1.277914
  opening:
    mode: "time_based"
    value: "08h00"
  closing:
    mode: "sun_based"
    value: "30m"
door:
  openening_duration: "65s"
  closing_duration: "60s"